# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: curdapp-secrets
  namespace: production
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "Sql054003"
  JWT_SECRET: "your-production-jwt-secret-key-change-this"
